### ISSUE TITLE
Add navigation to idiom pages (Next, Previous)

### ISSUE THREAD

**Issue by leviable** [Deleplace/programming-idioms#100]
I would like to click through the idioms in order. For instance, click on idiom #1, then click the next button to got to idiom #2, etc.

Please add Next and Previous buttons to the idiom pages to facility easier navigation through the idiom list. Additionally, it would be nice to have keyboard support build in (i.e. right arrow goes to next idiom, left arrow goes to previous idiom).

**Comment by Deleplace** [comment]
Hi Levi, the idioms are in no specific order so I had not thought about "next" and "previous".

Before we add more widgets, here are 2 alternatives:
- the dice icon in the topbar will take you to a random idiom
- the [cheatsheets](https://www.programming-idioms.org/about#about-block-cheatsheets) show _all_ of the implementations, for a given language

**Comment by leviable** [comment]
Thank for the reply, Deleplace. I appreciate the reluctance to add new widgets, so I thought I might expand on why I opened this issue.

I'm in the process of switching from Python to Golang, and wanted to spend a few minutes every day working through the idioms, say 10 a day. My only issue with the Dice is that once you've hit the 50% mark, it gets increasingly less likely that a click will return an idiom you haven't seen previously. Additionally, on a cursory viewing of the idioms (and acknowledging there is no explicit order), it seems the lower numbered ones are more common, and the higher numbered ones more esoteric.

For the Cheatsheets, while they do certainly offer a handy way to view the idioms for a single language, they don't (easily) allow for the comparison between languages.

In any event, thank you again for the reply, and feel free to close this issue if you'd like.

**Comment by Deleplace** [comment]
Ah, I love the idea of trying Go :)

The use case "get familiar with language Y when I already know language X" is actually central to the purpose of Programming idioms. I think the Cheatsheets could be made more useful with the option to print 2 language columns side-by-side so I created issue #101

I do intend to design and deploy a more "stripped down" UI in a couple of weeks. Would you be interested in giving your feedback on the beta of the new UI before it goes live, e.g. on the navigation UX? Thanks a lot for your interest in the project, I love the feedback even if I can't implement every idea in the end!

**Comment by Deleplace** [comment]
@leviable The side-by-side cheatsheet is released e.g. https://programming-idioms.org/cheatsheet/Python/Go

(though I ack there is still no direct way to navigate from idiom N to idiom N+1 in the individual idiom pages)

**Comment by Deleplace** [comment]
See also #192 Keyboard shortcuts

**Comment by Deleplace** [comment]
@leviable It is now possible to quickly browse the idioms with the keys P (previous) and N (next)

**Comment by Deleplace** [comment]
Links "Previous" and "Next" added at the top of the right column

![image](https://user-images.githubusercontent.com/13508141/154969462-284116f1-e42d-412a-bac9-00509717d392.png)
