### ISSUE TITLE
Multiple column cheatsheet

### ISSUE THREAD

**Issue by Deleplace** [Deleplace/programming-idioms#101]
Existing cheatsheets are for a single language, e.g. https://www.programming-idioms.org/cheatsheet/Go

It would be great to allow selecting at least 2 or 3 languages, to get a visual comparison of 2 or 3 languages over many "idioms".

**Comment by mgroovy** [comment]
That indeed sounds like a very interesting feature to quickly compare language syntax/brevity/... :-)

**Comment by Deleplace** [comment]
Done for 2 languages, see https://programming-idioms.org/about#about-block-cheatsheets

**Comment by mgroovy** [comment]
Hi @Deleplace, is it intentional that one can only select a select number of languages (e.g. not Groovy) for side by side comparison ?

**Comment by Deleplace** [comment]
I'm really sorry that the UI indeed gives this wrong impression. For "other languages" (not displayed in the dropdown) one must start typing in the text box, and accept autocompletion. Groovy is a valid choice, as well as the 30 other supported languages: https://programming-idioms.org/cheatsheet/Java/Groovy

**Comment by Deleplace** [comment]
The dropdown with only 10 languages is just confusing, I should trash it and keep only the text field with autocomplete.

This will be much more straightforward and unambiguous.

**Comment by Deleplace** [comment]
Done

![image](https://user-images.githubusercontent.com/13508141/100802233-62c03800-3429-11eb-9962-8a05113d5e8e.png)

**Comment by mgroovy** [comment]
Agree, much less confusing 👍
