### ISSUE TITLE
Question: purpose of language short names?

### ISSUE THREAD

**Issue by JayAndCatchFire** [Deleplace/programming-idioms#123]
I was a little confused when I saw the names like "Eli xir" and "Has kell".

https://github.com/Deleplace/programming-idioms/blob/13485d13e2fe81f4a1dcb7fdb88a51f4b88ed894/pig/languageName.go#L93-L124
https://github.com/Deleplace/programming-idioms/blob/cb476fa021aa84ddddd96cb4ebee7ffa4187621b/pigapp/templates.go#L25
https://github.com/Deleplace/programming-idioms/blob/80a87a7b7b01873b1340aa4fdb942f9a966c2a3a/pigapp/template/content/widget/language-coverage.html#L16

When I first saw this, I thought it was a typo or mistake.  The only purpose I can think of for this is to make sure columns stay thin on the [language coverage page](https://www.programming-idioms.org/about#about-block-language-coverage).

![Screen Shot 2020-05-06 at 12 06 43 PM](https://user-images.githubusercontent.com/10983817/81206674-1182bf80-8f92-11ea-80d3-2821c247b140.png)

One could argue that the names should be full-length.  Or that "Pas", "Clj", and "Py" should be "Pas cal", "Clo jure", and "Py thon" respectively.  (I'm not sure what to do about "scm" for Scheme. "Sch eme"?)  But in any case, can I suggest used the [`<wbr>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) tag instead of a space to indicate the indention of a word break?

**Comment by Deleplace** [comment]
It's indeed about keeping columns thin. Thanks for `<wbr>`, I was not aware of this option!

I'm still unsure of the best layout for these column headers, maybe tilt them 90' so their horizontal size is constant.

**Comment by Deleplace** [comment]
So I got rid of `PrintShortLang` and used some CSS verticalishness instead. More code removed than added!

```
$ git show f4b40c3 --oneline --shortstat
f4b40c3 (HEAD -> master, origin/master, origin/HEAD) issues/123 Language coverage vertical column headers.
 7 files changed, 23 insertions(+), 39 deletions(-)
```

![image](https://user-images.githubusercontent.com/13508141/81483369-02c03500-923e-11ea-832e-80e0722c4a9d.png)
