### ISSUE TITLE
Site is broken

### ISSUE THREAD

**Issue by 89z** [Deleplace/programming-idioms#142]
You cant see the code samples any more, example:

https://programming-idioms.org/idiom/175

workaround is `View`, `Page Style`, `No Style`.

**Comment by Deleplace** [comment]
Thank you Steven. A deployment went wrong around 18:30 UTC, then I rollbacked at 18:53 UTC.

The minified JS seemed to behave differently from the non-minified JS, not sure why yet.

**Comment by 89z** [comment]
I would be the original source is doing something dumb with ASI
