### ISSUE TITLE
Add Smalltalk language

### ISSUE THREAD

**Issue by Deleplace** [Deleplace/programming-idioms#150]
[Smalltalk](https://en.wikipedia.org/wiki/Smalltalk) is an object-oriented, dynamically typed reflective programming language.

**Comment by Deleplace** [comment]
Programming-Idioms is intended to host code in the most widely used languages, not in all the existing languages.
A new entry is possible only after a lot of users have requested it and are willing to contribute quality contents. Please add a comment to this page if you feel this language should be added.

**Comment by dvmason** [comment]
I was trying to add an idiom when I got a message that Smalltalk was not a supported language.

I think that is a huge shame, as Smalltalk is very important historically and increasingly important with a bunch of open-source implementations.

I also will be sharing your site with my students in a comparative languages course where we use Smalltalk, Elixir, Haskell, and Rust. So you already support 3 of those; it would be great if you also supported Smalltalk.

I will happily fill in many idioms for you for Smalltalk.

**Comment by dvmason** [comment]
Smalltalk is arguably more popular (at least in number of people programming in it) than at least Prolog, Dart, Cobol. Ada, Caml, and Fortran are debatable.

And I can certainly guarantee you I'll give you enough idioms that Smalltalk would soon be in your top 20 languages for idiom coverage - possibly top 5.

**Comment by noha** [comment]
Smalltalk should be added for having great ways solve those idiomatic approaches. It has some unique way of solving things just like LISP which is also present. And hey you have perl 😉 so what's up with the number of developers in it?

**Comment by GrahamMcLeod** [comment]
I support the addition of Smalltalk as a language to the site. 
I was first exposed to it in Byte in 1980, used it in academia from 1991 and we have used it in production software development consistently from 1998 till now. We use Visual Age Smalltalk / VA Smalltalk and Pharo implementations.

**Comment by girba** [comment]
Smalltalk would be a great addition.

**Comment by macta** [comment]
Yes, I'd like to see Smalltalk too as it often has interesting ways of thinking about problems (which ironically inspired other languages present)

**Comment by tesonep** [comment]
I support the adding of Smalltalk. It has a unique way of expressing solutions. I think it is useful to learners and experts to see alternative solutions to open their minds and progress as a whole programming community, even using different tools and languages you can get good ideas from everyone else.

**Comment by StephanEggermont** [comment]
Adding Smalltalk sounds like a good idea.

**Comment by chaetal** [comment]
Smalltalk is a must have!

**Comment by giorgioongithub** [comment]
Smalltalk should be added!

**Comment by krono** [comment]
I also would like to see and contribute to Smalltalk idioms

**Comment by bwbadger** [comment]
I think it is reasonable to say that Object Oriented programming is an idiom, and in that case Smalltalk should be most definitely included.  Smalltalk is, quite literally, the definitive Object Oriented language; Alan Kay who coined the phase Object Oriented did so to describe the project he was working on at the time, in the 70s at Xerox Parc.  That project was Smalltalk.  Smalltalk remains the best way to understand the idiom of Object Oriented programming.

**Comment by karstenBriksoft** [comment]
please add Smalltalk!

**Comment by cschucki** [comment]
As Wikipedia explains: "Smalltalk is also one of the most influential programming languages. Virtually all of the object-oriented languages that came after—Flavors, CLOS, Objective-C, Java, Python, Ruby,[15] and many others—were influenced by Smalltalk."

**Comment by LucFabresse** [comment]
thumbs up for Smalltalk!

**Comment by dariogithub** [comment]
Smalltalk... yes

**Comment by onierstrasz** [comment]
Kent Beck even wrote a book about Smalltalk idioms.

**Comment by Deleplace** [comment]
This is a popular request, wow!

Before we proceed, I'd like to clarify some information:

- Are there multiple flavors of Smalltalk, and if so are they fully compatible with each other? This is important because when we showcase an "idiomatic snippet in Smalltalk", we expect it to be working out of the box, copy-and-pastable. By design, variants of a language are not displayed as distinct languages. It is possible to specify in the comments "This works only for flavor X", but then the snippet is a bit less valuable for the visitor.
- Is there a good Smalltalk online website, where one can run some code, save it, and provide a stable URL for the "Demo" link of an idiom?
- I'm expecting several of the 16 Smalltalkers above to contribute some high-quality contents, i.e. snippets that are correct, link to the authoritative documentation, and link to a runnable demo. Would any of you also agree to speak in a video interview with myself, discussing the Smalltalk contributions? That would be truly awesome.

**Comment by StephanEggermont** [comment]
There are multiple flavors of Smalltalk. But they mostly differ in the platforms they run on and the supported libraries. Almost everything that would be considered idiomatic smalltalk (and uses the standard library) would run on all dialects.

**Comment by hguhl** [comment]
Smalltalk is a must have. No other language comes close to Smalltalk when it comes to expressive power. Smalltalk idioms are closer to human thinking than any other language.

**Comment by sumim** [comment]
How about writing idiom in the relatively popular [Pharo Smalltalk](https://pharo.org) flavor?

If there need to modify an idiom for other major flavors ([VisualWorks](https://cincomsmalltalk.com), [VA Smalltalk](https://instantiations.com/vast-platform), [Squeak](https://squeak.org), [GNU Smalltalk](https://smalltalk.gnu.org) , etc), I think you can use the "Explain stuff" section to add comments and modified code.

Although you can't run it directly on the web, the Pharo Smalltalk environment has a service ([Shared Smalltalk Workspaces](http://ws.stfx.eu/)) that can publish snippets written in your Playground to the web for other users to read and run in their own Playground easily (for example, http://ws.stfx.eu/3REX2WVKMBVJ ). How about using this URL for "Demo" link.

FYI; For GNU Smalltalk, you can use [Ideone](https://ideone.com) or [Coding Ground](https://tutorialspoint.com/execute_smalltalk_online.php) like other languages.

FYI2; For Squeak, you can run the environment on the web browser by using [SqueakJS](https://squeak.js.org).

**Comment by GrahamMcLeod** [comment]
I support the idea of summit above. Would add:
Pharo is open source and can be easily downloaded as s "one click image" for multiple platforms. This would allow interested parties to easily have a runtime / IDE environment on their environment within minutes. Code can be downloaded into that directly from Github. 
Pharo and Squeak are also relatively close with Pharo being a fork from Squeak (way back). 
Pharo code can also be run in the browser with PharoJS, in similar vein to SqueakJS.

**Comment by StephanEggermont** [comment]
From most of the responders above I know that they have experience with multiple flavors and are able to write snippets in a form that allows them to avoid issues.

**Comment by dvmason** [comment]
Actually, it would be very useful to have a Smalltalk web-playground that (a) started up quickly, and (b) was newbie friendly. This would be fairly easy to pull together with PharoJS, so I will work on that. (won't be tomorrow, but should be "soon")

**Comment by macta** [comment]
@dvmason worth noting that CodeParadise already has a minimal (900k) Pharo compatible image that loads with SqueakJS - it just needs a trivial ui to execute code examples and show the output (of course a PharoJS solution would also be cool, but it would be very quick to do a CP version and Erik might even host it)

**Comment by Deleplace** [comment]
Indeed, a full client-based playground (implemented in JS or WASM) would be awesome, and seems feasible.

For the UX, the playgrounds for [Go](https://play.golang.org/), [Rust](https://play.rust-lang.org/), [Dart](https://dartpad.dev/) are fine examples.

The other approach "execute the Smalltalk code server-side" is much more error-prone, because of (1) crypto mining abuse and (2) security hazard of running arbitrary user-provided code.

The snippets themselves can be stored server-side (like Go, and also Rust) or in Gist (like Dartpad, and also Rust).

**Comment by bwbadger** [comment]
Valentin, if you'd like to come along to the next UK Smalltalk User group meeting we could go over any questions you may have, and ideas others may have.  This is the meetup:  https://www.meetup.com/UKSTUG/

**Comment by dvmason** [comment]
@Deleplace when will this be live so we can start contributing? We have a prototype server-based REPL, working on making it bulletproof first, then we'll improve on the GUI/UX.  But I don't think we should need to wait for this before you add Smalltalk to your list. Most of your existing languages don't have Demo links (I looked at e.g. #19 - reverse, and only a handful have Demos), and once our REPL is ready it will be trivial to add the Demo link.

Thank you for creating this site. It will really help my students.

**Comment by ChristopheTouze** [comment]
Please add Smalltalk !

**Comment by ccrraaiigg** [comment]
Well said, Sebastian. Greetings, Valentin and all.

The https://squeak.js.org virtual machine runs all the currently active open-source Smalltalk distributions, including Pharo, in all JS environments, including web browsers, VSCode, NodeJS, etc.

I'd be happy to help with content and interviews. My current work integrating Smalltalk with Web technologies is at https://caffeine.js.org , and my blog is https://thiscontext.com/. I also co-organize the California Smalltalkers meetup group, and I'd be pleased to host any gatherings relevant to this effort.

**Comment by Deleplace** [comment]
Hello folks, after popular demand, I've **opened the contributions to Smalltalk**  :tada:  

![image](https://user-images.githubusercontent.com/13508141/131818749-820fcf1c-9a2d-4fbb-b3dc-b52c002e11a9.png)

I am very excited about having new contributors from this thread.

Could you please consider that Programming-Idioms' biggest challenge is **the quality of the contents**, which is currently too low on average for many languages. It is now on all of us to build a great curated collection of high-quality Smalltalk snippets, with links to official documentation.

**Comment by Deleplace** [comment]
I'm still considering deploying a service for runnable Smalltalk demos: #157. I'm also intending to interview some of you. Stay tuned!
