### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by plodgers** [Deleplace/programming-idioms#220]
I am VERY new to this - Progamming Idioms asks me to indicate my favourite languages - all there, except .... Logo.  Perhaps it is now redundant - but I found it a powerful language - and used it for orbital simulations - it looks like a joke as the cursor is by default a turtle - but it was great for recursion.  

Anyway - a bit much for me to take on at this stage, maybe for later or if someone else wants to take it on.

https://en.wikipedia.org/wiki/Logo_(programming_language)

**Comment by Deleplace** [comment]
I created #221.  However this is likely not to land, as Logo is not used much in production (it's an educational language).

**Comment by plodgers** [comment]
I came across this quite accidentally - Surprisingly Logo is still in use!

https://www.coursera.org/projects/mycelium

Paul Odgers
Reply to ***@***.***

Aliases for the same emailbox
***@***.***
***@***.***

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Deleplace** [comment]
Closing, follow-up in #221
