### ISSUE TITLE
[BUG] Too many closing parentheses in the python entry for idiom #177

### ISSUE THREAD

**Issue by brandonmarken** [Deleplace/programming-idioms#237]
I was browsing some idioms when suddenly I noticed that the Python entry for idiom #177 "find files for a list of file extensions" had an unmatched parentheses according to my syntax highlighting. I ran the the example shown and it gave me this error 

SyntaxError: closing parenthesis ')' does not match opening parenthesis '['

The example as shown is 
```
import glob, os
extensions = [".jpg", ".jpeg", ".png"]
L = [f for f in glob.glob(os.path.join(D, "**/*"), recursive=True)) if os.path.splitext(f)[1] in extensions]
```
the line beginning with L= needs to be changed to 
```
L = [f for f in glob.glob(os.path.join(D, "**/*"), recursive=True) if os.path.splitext(f)[1] in extensions]
```
Note there is only one closing parenthesis after "recursive=True"

**Comment by Deleplace** [comment]
Thanks!
