### ISSUE TITLE
[BUG] Several descriptions of the "Idioms" have been changed to "Mr."

### ISSUE THREAD

**Issue by Bart-B** [Deleplace/programming-idioms#243]
See the below copied text of the page (sorted by Language = Pascal)
```
# 10 	[Mr.]						
# 100 	[Mr.]						
# 2 	[Print Hello 10 times]	
# 6 	[Iterate over list values]	
# 12 	[Mr.]
```
When opening any of these "Mr.", the description lloks something like:
```
Idiom #10
1.
```
It looks like appr. 105 issues are affected in this way.  
Screenshot attached.  
![screenshot-programming-idioms](https://github.com/user-attachments/assets/738f0842-f8a9-4e7a-8d49-92239f8f6f20)

**Comment by Bart-B** [comment]
@Deleplace Maybe the site has been hacked??

**Comment by Bart-B** [comment]
It seems that a user called "lxbfYeaa" is responsible for this?

**Comment by Deleplace** [comment]
Thank you Bart, I confirm some automated vandalism made a large number of edits. I reverted them. We may find some more, now or in the future.

**Comment by simonvonhackewitz** [comment]
[idiom 346](https://www.programming-idioms.org/history/346) is also affected
