### ISSUE TITLE
No way to delete idioms

### ISSUE THREAD

**Issue by schveiguy** [Deleplace/programming-idioms#3]
Example: http://www.programming-idioms.org/idiom/71/echo-program-implementation has 2 `D` solutions, both are pretty much identical, one is slightly better than the other. Either this was due to a race between submitters, or one person didn't want to overwrite the other's solution (probably the latter). Clearly, both of them shouldn't be there.

**Comment by Deleplace** [comment]
Currently, only the admin may delete an idiom or an implementation! And he shall.

**Comment by schveiguy** [comment]
Well, then, maybe a way to flag down the admin about such a situation ;)

**Comment by JayAndCatchFire** [comment]
Similarly, maybe there should be some automatic deduplication?  For example, [pick-a-random-element-from-a-list](https://www.programming-idioms.org/idiom/11/pick-a-random-element-from-a-list) has two identical entries for lisp.

**Comment by Deleplace** [comment]
"Delete for all users" and "Auto dedupe" are not on the roadmap, as the mix of risk/complexity/expected benefits wouldn't meet the bar on my side.

On the other hand, I'm a big fan of @schveiguy 's suggestion of a "Flag for admin" button.

**Comment by Deleplace** [comment]
I implemented the "Flag for admin" button. I acknowledge this is not exactly the requested feature, it's all about tradeoff when it comes to let users contribute, but not destroy everything too easily.

![image](https://user-images.githubusercontent.com/13508141/82450500-12951000-9aad-11ea-8773-849a05973571.png)
