### ISSUE TITLE
Add language Elixir

### ISSUE THREAD

**Issue by Deleplace** [Deleplace/programming-idioms#31]
See http://elixir-lang.org/ about Elixir.

Programming-Idioms is not intended to host code in all languages, only the most widely used languages.
A new entry is possible only after a lot of users have requested it. Please add a comment to this page if you feel this language should be added.

**Comment by jwarlander** [comment]
I'd certainly like to see support for it; Elixir is a language that's quickly gaining traction.

**Comment by Anonyfox** [comment]
+1

**Comment by rrrene** [comment]
+1

**Comment by c-rack** [comment]
+1

**Comment by pcmarks** [comment]
+1

**Comment by HirofumiTamori** [comment]
+1

**Comment by simonprev** [comment]
+1

**Comment by djm** [comment]
+1

**Comment by anandubajith** [comment]
+1

**Comment by jfacorro** [comment]
+1

**Comment by InoMurko** [comment]
+1

**Comment by elbrujohalcon** [comment]
+1

**Comment by flaviogranero** [comment]
+1

**Comment by Nyco** [comment]
+42

**Comment by Joe-ESL** [comment]
+1

**Comment by knewter** [comment]
:+1:

**Comment by stevedomin** [comment]
:+1:

**Comment by ventsislaf** [comment]
:+1:

**Comment by vol0da** [comment]
+1

**Comment by the-guitarman** [comment]
+1

**Comment by Deleplace** [comment]
That's what I call traction!  Okay, let's add it.

**Comment by jwarlander** [comment]
Great! Looking forward to contributing!

**Comment by Deleplace** [comment]
Done. Have fun! Hope to see at least 1 implementation from each upvoter, not kidding!

You may teleport you with this link : 
www.programming-idioms.org/random-idiom/not-having/Elixir

**Comment by Anonyfox** [comment]
just did a few :)

**Comment by yeongsheng-tan** [comment]
(+1)

**Comment by yeongsheng-tan** [comment]
+1

**Comment by oldfartdeveloper** [comment]
+1

**Comment by seantanly** [comment]
+1

**Comment by tjgillies** [comment]
+1
