### ISSUE TITLE
Speed up the Language coverage page

### ISSUE THREAD

**Issue by Ripounet** [Deleplace/programming-idioms#56]
- Make 2 cases: (a) general, cached case and (b) case for users having favlangs.
- In case (a), add browser public cache headers, and keep the generated HTML in memcache. Remember to invalidate the cache when an impl is added/removed.
- In case (b), consider putting  the generated HTML in memcache for a few minutes, for the given set of favlangs. Find if it is possible to speed up template processing (600ms on GAE??).

**Comment by Deleplace** [comment]
82023ad is a good start.

Public cache headers might not be necessary for 28KB of (gzipped) html.

There are still some seconds to optimize, in Firefox, _before_ the load event, thus even before the request to `block-about-language-coverage`.
