### ISSUE TITLE
Add language Kotlin

### ISSUE THREAD

**Issue by Deleplace** [Deleplace/programming-idioms#73]
See http://kotlinlang.org/ about Kotlin.

Programming-Idioms is not intended to host code in all languages, only the most widely used languages.
A new entry is possible only after a lot of users have requested it. Please add a comment to this page if you feel this language should be added.

**Comment by renatoathaydes** [comment]
Hey guys, Kotlin is rapidly becoming a very popular language, specially after it became the language-of-choice on Android, endorsed by Google itself... the Programming Idioms website is awesome and Kotlin definitely deserves to be in it!

Hope you get around to adding it soon!

**Comment by Deleplace** [comment]
Done!
Let's add snippets in Kotlin!
