### ISSUE TITLE
Save the princess - how to insert image ?

### ISSUE THREAD

**Issue by BBasile** [Deleplace/programming-idioms#74]
I have the D version: 

![](https://68.media.tumblr.com/aa1b5a4915be162144b6a04da496542c/tumblr_ogycbfsNUo1uaaoreo1_1280.png)

**Comment by Deleplace** [comment]
That's great, very funny thanks!! (though kinda subjective)
The special page with comic strips is protected, I'll add the D version
when I come back from vacation.
Cheers
Val

**Comment by BBasile** [comment]
I don't know if that's great, funny or even subjective but it comes from here: https://dlangcomicstrips.tumblr.com/. I have myself no skill neither time for this kind of bullshits.
I think that the message in the background is simply that D get often underestimated, snubbed or even ignored.

**Comment by Deleplace** [comment]
Done
http://www.programming-idioms.org/idiom/149/save-the-princess/2069/d

2017-07-26 19:59 GMT+02:00 Basile Burg <notifications@github.com>:
