### ISSUE TITLE
Add Awk

### ISSUE THREAD

**Issue by cup** [Deleplace/programming-idioms#80]
please and thank you

- http://wikipedia.org/wiki/AWK
- http://pubs.opengroup.org/onlinepubs/9699919799/utilities/awk.html

**Comment by Deleplace** [comment]
Bash, Zsh, Awk, Sed, are interesting but not really comparable with programming languages. This would be material for a new project "shell-idioms.org".

**Comment by cup** [comment]
@Deleplace as Awk was the precursor to Perl, would you be ok with me adding Awk examples under Perl with a comment explaining that its Awk code?

notice that other sites allow Awk:

- http://rosettacode.org/wiki/Category:AWK
- http://hyperpolyglot.org/data

**Comment by Deleplace** [comment]
Hi Steven, thanks for the thoughtful question (I really appreciate that you asked before adding awk snippets).
Also, thanks for the nice "Format a number with grouped thousands" idiom!

I prefer that we don't mix Perl and Awk, as we strive to avoid confusion.
And despite its historical interest and its relevance today, I doubt that Awk fits into what Programming-Idioms is trying to showcase.

OTOH, a spin-off Shell-Idioms would not be hard to deploy. It would need a maintainer and some contributors. Would you be interested in such a project?

**Comment by cup** [comment]
I would rather see them under the same site, but something is better than nothing

i like your site because its very easy to contribute - you dont even have to register

shell and awk can accomplish tasks many different ways - so i can see a site like that being very effective
