### ISSUE TITLE
Include timestamp with edits

### ISSUE THREAD

**Issue by cup** [Deleplace/programming-idioms#85]
On the home page some examples are available under "Last updated"

but then if you go to an example, you cant see when it was last updated

i think page should have a timestamp, so you know when it was edited - something
like:

- Last updated 2018-9-19 11:23
- Last modified 2018-9-19 11:23
- Edited 2018-9-19 11:23

**Comment by Deleplace** [comment]
The "idiom history" aims to address this.
It is in the "actions" menu, but displayed only onwide screen (menu hidden on mobile portrait mode).

Note that there is 1 history per idiom, with all its implementations edits.

**Comment by cup** [comment]
ah yes that is great

thanks
