### ISSUE TITLE
Warning: Potential Security Risk Ahead

### ISSUE THREAD

**Issue by cup** [Deleplace/programming-idioms#91]
these links are all good:

- http://programming-idioms.org
- http://www.programming-idioms.org
- https://www.programming-idioms.org

but this link causes a problem:

https://programming-idioms.org

**Comment by Deleplace** [comment]
Thanks Steven for this alert. Can you please share some details? I tried the last link in Chrome and Firefox, but didn't see any warning in the Network tab, nor in the console, nor in the secure green lock.

**Comment by cup** [comment]
looks like it was a temporary issue in the certificate chain. im not sure how to capture that, maybe `curl -v`? if it happens again i will provide more info

thanks
