### ISSUE TITLE
Add attribution credits for implementations

### ISSUE THREAD

**Issue by kitgrose** [Deleplace/programming-idioms#99]
When posting an implementation we are shown a balloon saying:

> You agree to publish under the CC-BY-SA License

The CC-BY-SA license requires attribution, which is impossible to give right now. This could be easily solved if the nickname of the author of a given implementation was available somewhere on an idiom page, collapsed away if necessary to avoid adding visual noise.

As-is it's not clear what purpose nicknames serve at all.

**Comment by Deleplace** [comment]
Hello Kit, the full history of an idiom can be accessed from the [Actions] menu. The author of an implementation is shown when we try to edit it. Indeed it would be useful to have the nickname available close to the snippet in the main view, while at the same time avoid clutter creep.
